version: "3.8"

services:
  db:
    image: postgres:14
    container_name: products_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: products_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: products
      JWT_SECRET: votre_secret_jwt_ultra_secure
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: products_frontend
    environment:
      REACT_APP_API_BASE_URL: http://backend:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
